name: Git Webhook Trigger

on:
  push:
    branches:
      - main  # or any other branch you want to monitor
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} 
        run: |
          curl -X POST $WEBHOOK_URL \
          -H "Content-Type: application/json" \
          -d '{
                "user": "${{ github.actor }}",
                "event": "${{ github.event_name }}",
                "action": "${{ github.event.action || 'push' }}",
                "commit": "${{ github.event.head_commit.message || github.event.pull_request.title }}",
                "url": "${{ github.event.head_commit.url || github.event.pull_request.html_url }}"
              }'
