name: Git Webhook Trigger

on:
  push:
    branches:
      - main  # or any branch you want to monitor
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Ensure you set this secret
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "Error: WEBHOOK_URL is not set"
            exit 1
          fi

          # Create a JSON payload with the necessary information
          json_payload=$(cat <<EOF
          {
            "user": "${{ github.actor }}",
            "event": "${{ github.event_name }}",
            "action": "${{ github.event.action || 'push' }}",
            "commit": "${{ github.event.head_commit.message || github.event.pull_request.title }}",
            "url": "${{ github.event.head_commit.url || github.event.pull_request.html_url }}"
          }
          EOF
          )

          # Log the payload to debug
          echo "Payload to send: $json_payload"

          # Check if the payload is empty
          if [[ -z "$json_payload" ]]; then
            echo "Error: Payload is empty"
            exit 1
          fi

          # Send the webhook notification
          response=$(curl -X POST "$WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d "$json_payload")

          echo "Response from webhook: $response"
