name: Webhook to Discord

on:
  pull_request:
    types: [opened, edited, closed, reopened]

jobs:
  send_to_discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Pull Request to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Add this secret in your GitHub repo settings
        run: |
          python3 discord_webhook.py
