name: Git Webhook Trigger

on:
  push:
    branches:
      - main  # or any branch you want to monitor
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Ensure you set this secret
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "Error: WEBHOOK_URL is not set"
            exit 1
          fi

          # Log the context variables
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action || 'push' }}"
          
          # Prepare to create a JSON payload
          commit_message="${{ github.event.head_commit.message || github.event.pull_request.title }}"
          commit_url="${{ github.event.head_commit.url || github.event.pull_request.html_url }}"

          # Log the values being used in the payload
          echo "Commit Message: $commit_message"
          echo "Commit URL: $commit_url"

          # Create a JSON payload with the necessary information
          json_payload=$(cat <<EOF
          {
            "user": "${{ github.actor }}",
            "event": "${{ github.event_name }}",
            "action": "${{ github.event.action || 'push' }}",
            "commit": "$commit_message",
            "url": "$commit_url"
          }
          EOF
          )

          # Log the payload to debug
          echo "Payload to send: $json_payload"

          # Check if the payload is empty or if critical values are missing
          if [[ -z "$json_payload" || "$commit_message" == "" || "$commit_url" == "" ]]; then
            echo "Error: Payload is empty or missing critical information"
            exit 1
          fi

          # Send the webhook notification
          response=$(curl -X POST "$WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d "$json_payload")

          echo "Response from webhook: $response"
