name: Webhook to Discord

on:
  pull_request:
    types: [opened, edited, closed, reopened]
  push:
    branches:
      - main  # Change 'main' to your main branch name if different

jobs:
  send_to_discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Event to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_EVENT_DATA: ${{ toJson(github.event) }}
        run: |
          python3 discord_webhook.py
